// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"journey/dao/model"
)

func newTCategory(db *gorm.DB, opts ...gen.DOOption) tCategory {
	_tCategory := tCategory{}

	_tCategory.tCategoryDo.UseDB(db, opts...)
	_tCategory.tCategoryDo.UseModel(&model.TCategory{})

	tableName := _tCategory.tCategoryDo.TableName()
	_tCategory.ALL = field.NewAsterisk(tableName)
	_tCategory.ID = field.NewInt32(tableName, "id")
	_tCategory.Name = field.NewString(tableName, "name")
	_tCategory.Description = field.NewString(tableName, "description")
	_tCategory.Pid = field.NewInt32(tableName, "pid")
	_tCategory.Status = field.NewInt32(tableName, "status")
	_tCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_tCategory.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tCategory.DeletedAt = field.NewField(tableName, "deleted_at")

	_tCategory.fillFieldMap()

	return _tCategory
}

type tCategory struct {
	tCategoryDo tCategoryDo

	ALL         field.Asterisk
	ID          field.Int32  // 主键id
	Name        field.String // 名称
	Description field.String // 描述
	Pid         field.Int32  // 上级id
	Status      field.Int32  // 是否显示0不展示1展示
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (t tCategory) Table(newTableName string) *tCategory {
	t.tCategoryDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tCategory) As(alias string) *tCategory {
	t.tCategoryDo.DO = *(t.tCategoryDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tCategory) updateTableName(table string) *tCategory {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.Pid = field.NewInt32(table, "pid")
	t.Status = field.NewInt32(table, "status")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tCategory) WithContext(ctx context.Context) *tCategoryDo {
	return t.tCategoryDo.WithContext(ctx)
}

func (t tCategory) TableName() string { return t.tCategoryDo.TableName() }

func (t tCategory) Alias() string { return t.tCategoryDo.Alias() }

func (t tCategory) Columns(cols ...field.Expr) gen.Columns { return t.tCategoryDo.Columns(cols...) }

func (t *tCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tCategory) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["pid"] = t.Pid
	t.fieldMap["status"] = t.Status
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tCategory) clone(db *gorm.DB) tCategory {
	t.tCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tCategory) replaceDB(db *gorm.DB) tCategory {
	t.tCategoryDo.ReplaceDB(db)
	return t
}

type tCategoryDo struct{ gen.DO }

func (t tCategoryDo) Debug() *tCategoryDo {
	return t.withDO(t.DO.Debug())
}

func (t tCategoryDo) WithContext(ctx context.Context) *tCategoryDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tCategoryDo) ReadDB() *tCategoryDo {
	return t.Clauses(dbresolver.Read)
}

func (t tCategoryDo) WriteDB() *tCategoryDo {
	return t.Clauses(dbresolver.Write)
}

func (t tCategoryDo) Session(config *gorm.Session) *tCategoryDo {
	return t.withDO(t.DO.Session(config))
}

func (t tCategoryDo) Clauses(conds ...clause.Expression) *tCategoryDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tCategoryDo) Returning(value interface{}, columns ...string) *tCategoryDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tCategoryDo) Not(conds ...gen.Condition) *tCategoryDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tCategoryDo) Or(conds ...gen.Condition) *tCategoryDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tCategoryDo) Select(conds ...field.Expr) *tCategoryDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tCategoryDo) Where(conds ...gen.Condition) *tCategoryDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tCategoryDo) Order(conds ...field.Expr) *tCategoryDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tCategoryDo) Distinct(cols ...field.Expr) *tCategoryDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tCategoryDo) Omit(cols ...field.Expr) *tCategoryDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tCategoryDo) Join(table schema.Tabler, on ...field.Expr) *tCategoryDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tCategoryDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *tCategoryDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tCategoryDo) Group(cols ...field.Expr) *tCategoryDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tCategoryDo) Having(conds ...gen.Condition) *tCategoryDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tCategoryDo) Limit(limit int) *tCategoryDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tCategoryDo) Offset(offset int) *tCategoryDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tCategoryDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tCategoryDo) Unscoped() *tCategoryDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tCategoryDo) Create(values ...*model.TCategory) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tCategoryDo) CreateInBatches(values []*model.TCategory, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tCategoryDo) Save(values ...*model.TCategory) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tCategoryDo) First() (*model.TCategory, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategory), nil
	}
}

func (t tCategoryDo) Take() (*model.TCategory, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategory), nil
	}
}

func (t tCategoryDo) Last() (*model.TCategory, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategory), nil
	}
}

func (t tCategoryDo) Find() ([]*model.TCategory, error) {
	result, err := t.DO.Find()
	return result.([]*model.TCategory), err
}

func (t tCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TCategory, err error) {
	buf := make([]*model.TCategory, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tCategoryDo) FindInBatches(result *[]*model.TCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tCategoryDo) Attrs(attrs ...field.AssignExpr) *tCategoryDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tCategoryDo) Assign(attrs ...field.AssignExpr) *tCategoryDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tCategoryDo) Joins(fields ...field.RelationField) *tCategoryDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tCategoryDo) Preload(fields ...field.RelationField) *tCategoryDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tCategoryDo) FirstOrInit() (*model.TCategory, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategory), nil
	}
}

func (t tCategoryDo) FirstOrCreate() (*model.TCategory, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategory), nil
	}
}

func (t tCategoryDo) FindByPage(offset int, limit int) (result []*model.TCategory, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tCategoryDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tCategoryDo) Delete(models ...*model.TCategory) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tCategoryDo) withDO(do gen.Dao) *tCategoryDo {
	t.DO = *do.(*gen.DO)
	return t
}
