// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"journey/dao/model"
)

func newTSystemUpdateLog(db *gorm.DB, opts ...gen.DOOption) tSystemUpdateLog {
	_tSystemUpdateLog := tSystemUpdateLog{}

	_tSystemUpdateLog.tSystemUpdateLogDo.UseDB(db, opts...)
	_tSystemUpdateLog.tSystemUpdateLogDo.UseModel(&model.TSystemUpdateLog{})

	tableName := _tSystemUpdateLog.tSystemUpdateLogDo.TableName()
	_tSystemUpdateLog.ALL = field.NewAsterisk(tableName)
	_tSystemUpdateLog.ID = field.NewInt32(tableName, "id")
	_tSystemUpdateLog.Version = field.NewString(tableName, "version")
	_tSystemUpdateLog.VersionName = field.NewString(tableName, "version_name")
	_tSystemUpdateLog.Content = field.NewString(tableName, "content")
	_tSystemUpdateLog.IntervalPeriod = field.NewInt32(tableName, "interval_period")
	_tSystemUpdateLog.MacDownloadURL = field.NewString(tableName, "mac_download_url")
	_tSystemUpdateLog.WindowDownloadURL = field.NewString(tableName, "window_download_url")
	_tSystemUpdateLog.CreatedAt = field.NewTime(tableName, "created_at")
	_tSystemUpdateLog.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tSystemUpdateLog.DeletedAt = field.NewField(tableName, "deleted_at")

	_tSystemUpdateLog.fillFieldMap()

	return _tSystemUpdateLog
}

type tSystemUpdateLog struct {
	tSystemUpdateLogDo tSystemUpdateLogDo

	ALL               field.Asterisk
	ID                field.Int32  // 主键id
	Version           field.String // 版本号
	VersionName       field.String // 安装包名称
	Content           field.String // 更新内容
	IntervalPeriod    field.Int32  // 新版本提醒的间隔周期，单位秒
	MacDownloadURL    field.String // mac下载地址
	WindowDownloadURL field.String // window下载地址
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间
	DeletedAt         field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (t tSystemUpdateLog) Table(newTableName string) *tSystemUpdateLog {
	t.tSystemUpdateLogDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tSystemUpdateLog) As(alias string) *tSystemUpdateLog {
	t.tSystemUpdateLogDo.DO = *(t.tSystemUpdateLogDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tSystemUpdateLog) updateTableName(table string) *tSystemUpdateLog {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.Version = field.NewString(table, "version")
	t.VersionName = field.NewString(table, "version_name")
	t.Content = field.NewString(table, "content")
	t.IntervalPeriod = field.NewInt32(table, "interval_period")
	t.MacDownloadURL = field.NewString(table, "mac_download_url")
	t.WindowDownloadURL = field.NewString(table, "window_download_url")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tSystemUpdateLog) WithContext(ctx context.Context) *tSystemUpdateLogDo {
	return t.tSystemUpdateLogDo.WithContext(ctx)
}

func (t tSystemUpdateLog) TableName() string { return t.tSystemUpdateLogDo.TableName() }

func (t tSystemUpdateLog) Alias() string { return t.tSystemUpdateLogDo.Alias() }

func (t tSystemUpdateLog) Columns(cols ...field.Expr) gen.Columns {
	return t.tSystemUpdateLogDo.Columns(cols...)
}

func (t *tSystemUpdateLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tSystemUpdateLog) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["version"] = t.Version
	t.fieldMap["version_name"] = t.VersionName
	t.fieldMap["content"] = t.Content
	t.fieldMap["interval_period"] = t.IntervalPeriod
	t.fieldMap["mac_download_url"] = t.MacDownloadURL
	t.fieldMap["window_download_url"] = t.WindowDownloadURL
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tSystemUpdateLog) clone(db *gorm.DB) tSystemUpdateLog {
	t.tSystemUpdateLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tSystemUpdateLog) replaceDB(db *gorm.DB) tSystemUpdateLog {
	t.tSystemUpdateLogDo.ReplaceDB(db)
	return t
}

type tSystemUpdateLogDo struct{ gen.DO }

func (t tSystemUpdateLogDo) Debug() *tSystemUpdateLogDo {
	return t.withDO(t.DO.Debug())
}

func (t tSystemUpdateLogDo) WithContext(ctx context.Context) *tSystemUpdateLogDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tSystemUpdateLogDo) ReadDB() *tSystemUpdateLogDo {
	return t.Clauses(dbresolver.Read)
}

func (t tSystemUpdateLogDo) WriteDB() *tSystemUpdateLogDo {
	return t.Clauses(dbresolver.Write)
}

func (t tSystemUpdateLogDo) Session(config *gorm.Session) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Session(config))
}

func (t tSystemUpdateLogDo) Clauses(conds ...clause.Expression) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tSystemUpdateLogDo) Returning(value interface{}, columns ...string) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tSystemUpdateLogDo) Not(conds ...gen.Condition) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tSystemUpdateLogDo) Or(conds ...gen.Condition) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tSystemUpdateLogDo) Select(conds ...field.Expr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tSystemUpdateLogDo) Where(conds ...gen.Condition) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tSystemUpdateLogDo) Order(conds ...field.Expr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tSystemUpdateLogDo) Distinct(cols ...field.Expr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tSystemUpdateLogDo) Omit(cols ...field.Expr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tSystemUpdateLogDo) Join(table schema.Tabler, on ...field.Expr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tSystemUpdateLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tSystemUpdateLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tSystemUpdateLogDo) Group(cols ...field.Expr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tSystemUpdateLogDo) Having(conds ...gen.Condition) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tSystemUpdateLogDo) Limit(limit int) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tSystemUpdateLogDo) Offset(offset int) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tSystemUpdateLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tSystemUpdateLogDo) Unscoped() *tSystemUpdateLogDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tSystemUpdateLogDo) Create(values ...*model.TSystemUpdateLog) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tSystemUpdateLogDo) CreateInBatches(values []*model.TSystemUpdateLog, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tSystemUpdateLogDo) Save(values ...*model.TSystemUpdateLog) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tSystemUpdateLogDo) First() (*model.TSystemUpdateLog, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSystemUpdateLog), nil
	}
}

func (t tSystemUpdateLogDo) Take() (*model.TSystemUpdateLog, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSystemUpdateLog), nil
	}
}

func (t tSystemUpdateLogDo) Last() (*model.TSystemUpdateLog, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSystemUpdateLog), nil
	}
}

func (t tSystemUpdateLogDo) Find() ([]*model.TSystemUpdateLog, error) {
	result, err := t.DO.Find()
	return result.([]*model.TSystemUpdateLog), err
}

func (t tSystemUpdateLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TSystemUpdateLog, err error) {
	buf := make([]*model.TSystemUpdateLog, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tSystemUpdateLogDo) FindInBatches(result *[]*model.TSystemUpdateLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tSystemUpdateLogDo) Attrs(attrs ...field.AssignExpr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tSystemUpdateLogDo) Assign(attrs ...field.AssignExpr) *tSystemUpdateLogDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tSystemUpdateLogDo) Joins(fields ...field.RelationField) *tSystemUpdateLogDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tSystemUpdateLogDo) Preload(fields ...field.RelationField) *tSystemUpdateLogDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tSystemUpdateLogDo) FirstOrInit() (*model.TSystemUpdateLog, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSystemUpdateLog), nil
	}
}

func (t tSystemUpdateLogDo) FirstOrCreate() (*model.TSystemUpdateLog, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSystemUpdateLog), nil
	}
}

func (t tSystemUpdateLogDo) FindByPage(offset int, limit int) (result []*model.TSystemUpdateLog, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tSystemUpdateLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tSystemUpdateLogDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tSystemUpdateLogDo) Delete(models ...*model.TSystemUpdateLog) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tSystemUpdateLogDo) withDO(do gen.Dao) *tSystemUpdateLogDo {
	t.DO = *do.(*gen.DO)
	return t
}
