// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTCategory = "t_category"

// TCategory mapped from table <t_category>
type TCategory struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	Name        string         `gorm:"column:name;not null;comment:名称" json:"name"`                    // 名称
	Description string         `gorm:"column:description;not null;comment:描述" json:"description"`      // 描述
	Pid         int32          `gorm:"column:pid;not null;comment:上级id" json:"pid"`                    // 上级id
	Status      int32          `gorm:"column:status;not null;comment:是否显示0不展示1展示" json:"status"`       // 是否显示0不展示1展示
	CreatedAt   time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`               // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`               // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`               // 删除时间
}

// TableName TCategory's table name
func (*TCategory) TableName() string {
	return TableNameTCategory
}
