// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTExportTask = "t_export_task"

// TExportTask mapped from table <t_export_task>
type TExportTask struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`     // 主键id
	UserID     int32          `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                // 用户id
	SqlText    string         `gorm:"column:sql_text;not null;comment:原生sql" json:"sql_text"`             // 原生sql
	FilePath   string         `gorm:"column:file_path;not null;comment:文件路径" json:"file_path"`            // 文件路径
	Status     int32          `gorm:"column:status;not null;default:1;comment:1待处理2已完成3失败" json:"status"` // 1待处理2已完成3失败
	FailReason string         `gorm:"column:fail_reason;not null;comment:失败原因" json:"fail_reason"`        // 失败原因
	CreatedAt  time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                   // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                   // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                   // 删除时间
}

// TableName TExportTask's table name
func (*TExportTask) TableName() string {
	return TableNameTExportTask
}
