// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTFeedback = "t_feedback"

// TFeedback mapped from table <t_feedback>
type TFeedback struct {
	ID            int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`    // 主键id
	UserID        int32          `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`               // 用户id
	ContractPhone string         `gorm:"column:contract_phone;not null;comment:手机号码" json:"contract_phone"` // 手机号码
	Content       string         `gorm:"column:content;not null;comment:反馈的内容" json:"content"`              // 反馈的内容
	CreatedAt     time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                  // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                  // 删除时间
}

// TableName TFeedback's table name
func (*TFeedback) TableName() string {
	return TableNameTFeedback
}
