// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTSystemUpdateLog = "t_system_update_log"

// TSystemUpdateLog mapped from table <t_system_update_log>
type TSystemUpdateLog struct {
	ID                int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                              // 主键id
	Version           string         `gorm:"column:version;not null;comment:版本号" json:"version"`                                          // 版本号
	VersionName       string         `gorm:"column:version_name;comment:安装包名称" json:"version_name"`                                       // 安装包名称
	Content           string         `gorm:"column:content;not null;comment:更新内容" json:"content"`                                         // 更新内容
	IntervalPeriod    int32          `gorm:"column:interval_period;not null;default:86400;comment:新版本提醒的间隔周期，单位秒" json:"interval_period"` // 新版本提醒的间隔周期，单位秒
	MacDownloadURL    string         `gorm:"column:mac_download_url;not null;comment:mac下载地址" json:"mac_download_url"`                    // mac下载地址
	WindowDownloadURL string         `gorm:"column:window_download_url;not null;comment:window下载地址" json:"window_download_url"`           // window下载地址
	CreatedAt         time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                            // 创建时间
	UpdatedAt         time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                            // 更新时间
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                            // 删除时间
}

// TableName TSystemUpdateLog's table name
func (*TSystemUpdateLog) TableName() string {
	return TableNameTSystemUpdateLog
}
