// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTTool = "t_tools"

// TTool mapped from table <t_tools>
type TTool struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`              // 主键id
	Mark        string         `gorm:"column:mark;not null;comment:工具标识" json:"mark"`                               // 工具标识
	Name        string         `gorm:"column:name;not null;comment:名称" json:"name"`                                 // 名称
	Logo        string         `gorm:"column:logo;not null;comment:工具图片" json:"logo"`                               // 工具图片
	Description string         `gorm:"column:description;not null;comment:描述" json:"description"`                   // 描述
	CategoryID  int32          `gorm:"column:category_id;not null;comment:分类id" json:"category_id"`                 // 分类id
	IsRecommend int32          `gorm:"column:is_recommend;not null;default:2;comment:是否推荐1是2否" json:"is_recommend"` // 是否推荐1是2否
	Router      string         `gorm:"column:router;not null;comment:路由跳转" json:"router"`                           // 路由跳转
	CreatedAt   time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                            // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                            // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                            // 删除时间
}

// TableName TTool's table name
func (*TTool) TableName() string {
	return TableNameTTool
}
