// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/goccy/go-json"
	"gorm.io/gorm"
)

const TableNameTUser = "t_user"

// TUser mapped from table <t_user>
type TUser struct {
	ID            int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	Phone         string         `gorm:"column:phone;not null;comment:手机号码" json:"phone"`                // 手机号码
	Account       string         `gorm:"column:account;not null;comment:用户账号" json:"account"`            // 用户账号
	Password      string         `gorm:"column:password;not null;comment:密码" json:"password"`            // 密码
	Nickname      string         `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`            // 昵称
	AvatarURL     string         `gorm:"column:avatar_url;not null;comment:头像" json:"avatar_url"`        // 头像
	VipLevelID    int32          `gorm:"column:vip_level_id;not null;comment:会员级别" json:"vip_level_id"`  // 会员级别
	VipExpireTime time.Time      `gorm:"column:vip_expire_time;comment:vip到期时间" json:"vip_expire_time"`  // vip到期时间
	CreatedAt     time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`               // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`               // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`               // 删除时间
}

// MarshalJSON 自定义时间格式输出（Y-m-d H:i:s）
func (u TUser) MarshalJSON() ([]byte, error) {
	type Alias TUser
	return json.Marshal(&struct {
		VipExpireTime string `json:"vip_expire_time"`
		CreatedAt     string `json:"created_at"`
		UpdatedAt     string `json:"updated_at"`
		DeletedAt     string `json:"deleted_at"`
		*Alias
	}{
		VipExpireTime: formatTime(u.VipExpireTime),
		CreatedAt:     formatTime(u.CreatedAt),
		UpdatedAt:     formatTime(u.UpdatedAt),
		DeletedAt:     formatDeletedAt(u.DeletedAt),
		Alias:         (*Alias)(&u),
	})
}

// formatTime 格式化普通时间
func formatTime(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format("2006-01-02 15:04:05")
}

// formatDeletedAt 格式化 gorm.DeletedAt
func formatDeletedAt(d gorm.DeletedAt) string {
	if d.Valid {
		return d.Time.Format("2006-01-02 15:04:05")
	}
	return ""
}

// TableName TUser's table name
func (*TUser) TableName() string {
	return TableNameTUser
}
