// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTUser = "t_user"

// TUser mapped from table <t_user>
type TUser struct {
	ID            int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	Phone         string         `gorm:"column:phone;not null;comment:手机号码" json:"phone"`                // 手机号码
	Account       string         `gorm:"column:account;not null;comment:用户账号" json:"account"`            // 用户账号
	Password      string         `gorm:"column:password;not null;comment:密码" json:"password"`            // 密码
	Nickname      string         `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`            // 昵称
	AvatarURL     string         `gorm:"column:avatar_url;not null;comment:头像" json:"avatar_url"`        // 头像
	VipLevelID    int32          `gorm:"column:vip_level_id;not null;comment:会员级别" json:"vip_level_id"`  // 会员级别
	VipExpireTime time.Time      `gorm:"column:vip_expire_time;comment:vip到期时间" json:"vip_expire_time"`  // vip到期时间
	CreatedAt     time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`               // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`               // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`               // 删除时间
}

// TableName TUser's table name
func (*TUser) TableName() string {
	return TableNameTUser
}
