// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTUserResetPassword = "t_user_reset_password"

// TUserResetPassword mapped from table <t_user_reset_password>
type TUserResetPassword struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	Account   string         `gorm:"column:account;not null;comment:找回账号" json:"account"`            // 找回账号
	UseEmail  string         `gorm:"column:use_email;not null;comment:使用的邮箱" json:"use_email"`       // 使用的邮箱
	Code      string         `gorm:"column:code;not null;comment:验证码" json:"code"`                   // 验证码
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`               // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`               // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`               // 删除时间
}

// TableName TUserResetPassword's table name
func (*TUserResetPassword) TableName() string {
	return TableNameTUserResetPassword
}
