// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"

	"gorm.io/gorm"
)

const TableNameTExportTask = "t_export_task"

// TExportTask mapped from table <t_export_task>
type TExportTask struct {
	ID           int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`     // 主键id
	UserID       int32          `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                // 用户id
	SqlText      string         `gorm:"column:sql_text;comment:原生执行sql" json:"sql_text"`                    // 原生执行sql
	CountSqlText string         `gorm:"column:count_sql_text;comment:执行统计的sql" json:"count_sql_text"`       // 执行统计的sql
	Process      float64        `gorm:"column:process;not null;default:0.00;comment:进度" json:"process"`     // 进度
	FilePath     string         `gorm:"column:file_path;not null;comment:文件路径" json:"file_path"`            // 文件路径
	Status       int32          `gorm:"column:status;not null;default:1;comment:1待处理2已完成3失败" json:"status"` // 1待处理2已完成3失败
	FailReason   string         `gorm:"column:fail_reason;not null;comment:失败原因" json:"fail_reason"`        // 失败原因
	CreatedAt    time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                   // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                   // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                   // 删除时间
}

// MarshalJSON 自定义时间格式输出（Y-m-d H:i:s）
func (u TExportTask) MarshalJSON() ([]byte, error) {
	type Alias TExportTask
	return json.Marshal(&struct {
		VipExpireTime string `json:"vip_expire_time"`
		CreatedAt     string `json:"created_at"`
		UpdatedAt     string `json:"updated_at"`
		DeletedAt     string `json:"deleted_at"`
		*Alias
	}{
		CreatedAt: formatTime(u.CreatedAt),
		UpdatedAt: formatTime(u.UpdatedAt),
		DeletedAt: formatDeletedAt(u.DeletedAt),
		Alias:     (*Alias)(&u),
	})
}

// TableName TExportTask's table name
func (*TExportTask) TableName() string {
	return TableNameTExportTask
}
