// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"journey/model"
)

func newTExportTask(db *gorm.DB, opts ...gen.DOOption) tExportTask {
	_tExportTask := tExportTask{}

	_tExportTask.tExportTaskDo.UseDB(db, opts...)
	_tExportTask.tExportTaskDo.UseModel(&model.TExportTask{})

	tableName := _tExportTask.tExportTaskDo.TableName()
	_tExportTask.ALL = field.NewAsterisk(tableName)
	_tExportTask.ID = field.NewInt32(tableName, "id")
	_tExportTask.UserID = field.NewInt32(tableName, "user_id")
	_tExportTask.SqlText = field.NewString(tableName, "sql_text")
	_tExportTask.FilePath = field.NewString(tableName, "file_path")
	_tExportTask.Status = field.NewInt32(tableName, "status")
	_tExportTask.FailReason = field.NewString(tableName, "fail_reason")
	_tExportTask.CreatedAt = field.NewTime(tableName, "created_at")
	_tExportTask.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tExportTask.DeletedAt = field.NewField(tableName, "deleted_at")

	_tExportTask.fillFieldMap()

	return _tExportTask
}

type tExportTask struct {
	tExportTaskDo tExportTaskDo

	ALL        field.Asterisk
	ID         field.Int32  // 主键id
	UserID     field.Int32  // 用户id
	SqlText    field.String // 原生sql
	FilePath   field.String // 文件路径
	Status     field.Int32  // 1待处理2已完成3失败
	FailReason field.String // 失败原因
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (t tExportTask) Table(newTableName string) *tExportTask {
	t.tExportTaskDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tExportTask) As(alias string) *tExportTask {
	t.tExportTaskDo.DO = *(t.tExportTaskDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tExportTask) updateTableName(table string) *tExportTask {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.UserID = field.NewInt32(table, "user_id")
	t.SqlText = field.NewString(table, "sql_text")
	t.FilePath = field.NewString(table, "file_path")
	t.Status = field.NewInt32(table, "status")
	t.FailReason = field.NewString(table, "fail_reason")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tExportTask) WithContext(ctx context.Context) *tExportTaskDo {
	return t.tExportTaskDo.WithContext(ctx)
}

func (t tExportTask) TableName() string { return t.tExportTaskDo.TableName() }

func (t tExportTask) Alias() string { return t.tExportTaskDo.Alias() }

func (t tExportTask) Columns(cols ...field.Expr) gen.Columns { return t.tExportTaskDo.Columns(cols...) }

func (t *tExportTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tExportTask) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["id"] = t.ID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["sql_text"] = t.SqlText
	t.fieldMap["file_path"] = t.FilePath
	t.fieldMap["status"] = t.Status
	t.fieldMap["fail_reason"] = t.FailReason
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tExportTask) clone(db *gorm.DB) tExportTask {
	t.tExportTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tExportTask) replaceDB(db *gorm.DB) tExportTask {
	t.tExportTaskDo.ReplaceDB(db)
	return t
}

type tExportTaskDo struct{ gen.DO }

func (t tExportTaskDo) Debug() *tExportTaskDo {
	return t.withDO(t.DO.Debug())
}

func (t tExportTaskDo) WithContext(ctx context.Context) *tExportTaskDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tExportTaskDo) ReadDB() *tExportTaskDo {
	return t.Clauses(dbresolver.Read)
}

func (t tExportTaskDo) WriteDB() *tExportTaskDo {
	return t.Clauses(dbresolver.Write)
}

func (t tExportTaskDo) Session(config *gorm.Session) *tExportTaskDo {
	return t.withDO(t.DO.Session(config))
}

func (t tExportTaskDo) Clauses(conds ...clause.Expression) *tExportTaskDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tExportTaskDo) Returning(value interface{}, columns ...string) *tExportTaskDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tExportTaskDo) Not(conds ...gen.Condition) *tExportTaskDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tExportTaskDo) Or(conds ...gen.Condition) *tExportTaskDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tExportTaskDo) Select(conds ...field.Expr) *tExportTaskDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tExportTaskDo) Where(conds ...gen.Condition) *tExportTaskDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tExportTaskDo) Order(conds ...field.Expr) *tExportTaskDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tExportTaskDo) Distinct(cols ...field.Expr) *tExportTaskDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tExportTaskDo) Omit(cols ...field.Expr) *tExportTaskDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tExportTaskDo) Join(table schema.Tabler, on ...field.Expr) *tExportTaskDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tExportTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tExportTaskDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tExportTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *tExportTaskDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tExportTaskDo) Group(cols ...field.Expr) *tExportTaskDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tExportTaskDo) Having(conds ...gen.Condition) *tExportTaskDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tExportTaskDo) Limit(limit int) *tExportTaskDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tExportTaskDo) Offset(offset int) *tExportTaskDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tExportTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tExportTaskDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tExportTaskDo) Unscoped() *tExportTaskDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tExportTaskDo) Create(values ...*model.TExportTask) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tExportTaskDo) CreateInBatches(values []*model.TExportTask, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tExportTaskDo) Save(values ...*model.TExportTask) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tExportTaskDo) First() (*model.TExportTask, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExportTask), nil
	}
}

func (t tExportTaskDo) Take() (*model.TExportTask, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExportTask), nil
	}
}

func (t tExportTaskDo) Last() (*model.TExportTask, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExportTask), nil
	}
}

func (t tExportTaskDo) Find() ([]*model.TExportTask, error) {
	result, err := t.DO.Find()
	return result.([]*model.TExportTask), err
}

func (t tExportTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TExportTask, err error) {
	buf := make([]*model.TExportTask, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tExportTaskDo) FindInBatches(result *[]*model.TExportTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tExportTaskDo) Attrs(attrs ...field.AssignExpr) *tExportTaskDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tExportTaskDo) Assign(attrs ...field.AssignExpr) *tExportTaskDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tExportTaskDo) Joins(fields ...field.RelationField) *tExportTaskDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tExportTaskDo) Preload(fields ...field.RelationField) *tExportTaskDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tExportTaskDo) FirstOrInit() (*model.TExportTask, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExportTask), nil
	}
}

func (t tExportTaskDo) FirstOrCreate() (*model.TExportTask, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExportTask), nil
	}
}

func (t tExportTaskDo) FindByPage(offset int, limit int) (result []*model.TExportTask, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tExportTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tExportTaskDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tExportTaskDo) Delete(models ...*model.TExportTask) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tExportTaskDo) withDO(do gen.Dao) *tExportTaskDo {
	t.DO = *do.(*gen.DO)
	return t
}
